### ISSUE TITLE
convert is not found in gradle environement 

### ISSUE THREAD

**Issue by ChrisArenas** [eowise/gradle-imagemagick#3]
The path to the convert commandLine Tool is not resolved properly from gradle under Mac OS.
Please add some customizability or request the path to convert with a "which" command.

**Comment by leruaa** [comment]
I don't know how Mac OS works, but is convert in a "path" environment variable ?

**Comment by ChrisArenas** [comment]
pew, finally i found the right spot to tell Gradle where to look. I still don't know why it is different working to other commands but i had to add my path to launchd.conf
